-- ============================================================
-- IMPORTAÇÃO FINANCEIRA — Reconecte
-- 505 lançamentos (27/03/2025 a 17/04/2026)
-- Extraído de relatorio-extrato.xls (PsicoManager)
-- ATENÇÃO: rode apenas uma vez no Supabase SQL Editor
-- ============================================================

INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Liliane F Santos Leite', 'Sessões', '2025-03-27', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'DARF', 'DARF', '2025-04-01', 42.18);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'ISS', 'ISS', '2025-04-01', 186.52);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-04-01', 3043.04);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-04-01', 976.97);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2025-04-01', 14.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Hospedagem Site', 'Hospedagem Site', '2025-04-01', 54.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Contabilidade', 'Contabilidade', '2025-04-01', 160.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'INSS', 'INSS', '2025-04-01', 166.98);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Água', 'Água', '2025-04-01', 147.78);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Energia elétrica', 'Energia elétrica', '2025-04-01', 156.79);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Internet', 'Internet', '2025-04-01', 108.18);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2025-04-01', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Investimento da Empresa - BTC', 'Investimento da Empresa', '2025-04-01', 3000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tallytta Sarah V Silva', 'Sessões', '2025-04-01', 240.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carlos Augusto', 'Sessões', '2025-04-01', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lorena Cabral Silveira', 'Sessões', '2025-04-02', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-04-03', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-04-03', 444.49);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carlos Felipe de Medeiros Bernadino', 'Sessões', '2025-04-03', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-04-04', 2000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-04-08', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Elton Fernandes dos Santos', 'Sessões', '2025-04-10', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Elton Fernandes dos Santos', 'Sessões', '2025-04-10', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lauany', 'Sessões', '2025-04-10', 400.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Joseline Paes Rech de França', 'Sessões', '2025-04-10', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Danilo', 'Sessões', '2025-04-10', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Alexandra Nunes de Souza', 'Sessões', '2025-04-11', 450.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Alexandra Nunes de Souza', 'Sessões', '2025-04-11', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Alexandra Nunes de Souza', 'Sessões', '2025-04-11', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Kleber', 'Sessões', '2025-04-11', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lorena Souto', 'Sessões', '2025-04-14', 400.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ednilson Brito Lopes', 'Sessões', '2025-04-14', 400.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Joseline Paes Rech de França', 'Sessões', '2025-04-14', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Joseline Paes Rech de França', 'Sessões', '2025-04-14', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Edson', 'Sessões', '2025-04-14', 600.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tallytta Sarah V Silva', 'Sessões', '2025-04-15', 240.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', '- - Psicóloga 01 - Semana 03', NULL, '2025-04-19', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-04-20', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-04-20', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-04-22', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucy Assef', 'Sessões', '2025-04-22', 400.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tallytta Sarah V Silva', 'Sessões', '2025-04-25', 240.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', '- - Psicóloga 01 - Semana 04', NULL, '2025-04-26', 315.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-04-26', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Liliane F Santos Leite', 'Sessões', '2025-04-26', 500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', '- - Secretária', NULL, '2025-04-30', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Cleudiane', 'Sessões', '2025-04-30', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Contabilidade - Deise', 'Contabilidade', '2025-05-01', 160.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2025-05-01', 14.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Hospedagem Site', 'Hospedagem Site', '2025-05-01', 54.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Internet', 'Internet', '2025-05-01', 108.18);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2025-05-01', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-05-01', 890.53);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-05-01', 1964.09);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2025-05-01', 120.18);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'DARF', 'DARF', '2025-05-01', 186.50);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Água', 'Água', '2025-05-02', 147.78);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tirza Almeida Deschamps', 'Sessões', '2025-05-03', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Jairo Costa e Silva', 'Sessões', '2025-05-03', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'DARF', 'DARF', '2025-05-05', 186.50);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-05', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-05', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Energia elétrica', 'Energia elétrica', '2025-05-05', 231.07);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tirza Almeida Deschamps', 'Sessões', '2025-05-06', 400.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Jefferson de Souza Pinto', 'Sessões', '2025-05-07', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Jefferson de Souza Pinto', 'Sessões', '2025-05-07', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucilla Amaral Neder', 'Sessões', '2025-05-08', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucilla Amaral Neder', 'Sessões', '2025-05-08', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Mateus de Oliveira', 'Sessões', '2025-05-10', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-12', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-12', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ana Carolina de Oliveira', 'Sessões', '2025-05-12', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ana Carolina de Oliveira', 'Sessões', '2025-05-12', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Natan Lemes', 'Sessões', '2025-05-13', 2000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Implemantação - Ia + Kommo', 'Implemantação - Ia + Kommo', '2025-05-14', 2500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Investimento da Empresa - BTC', 'Investimento da Empresa', '2025-05-14', 3000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rafael', 'Sessões', '2025-05-14', 750.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Elton Fernandes dos Santos', 'Sessões', '2025-05-14', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lorena Souto', 'Sessões', '2025-05-14', 400.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ednilson Brito Lopes', 'Sessões', '2025-05-14', 400.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ednilson Brito Lopes', 'Sessões', '2025-05-14', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Fernando Giordano', 'Sessões', '2025-05-15', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carlos Rocha', 'Sessões', '2025-05-16', 2300.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-17', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-17', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-17', 140.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tallytta Sarah V Silva', 'Sessões', '2025-05-17', 240.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-05-19', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucy Assef', 'Sessões', '2025-05-19', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Joseline Paes Rech de França', 'Sessões', '2025-05-19', 180.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Renata Martins', 'Sessões', '2025-05-19', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ana Carolina Silveira Bevilaqua', 'Sessões', '2025-05-19', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Juliano Mateus ferreira', 'Sessões', '2025-05-19', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Juliano Mateus ferreira', 'Sessões', '2025-05-19', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Mara Cely dos Santos Fernandes', 'Sessões', '2025-05-19', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-24', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-24', 175.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Liliane F Santos Leite', 'Sessões', '2025-05-26', 500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Fernando Giordano', 'Sessões', '2025-05-26', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Beatriz Melo', 'Sessões', '2025-05-26', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lais Braga Arruda', 'Sessões', '2025-05-30', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Willy Sarahan', 'Sessões', '2025-05-30', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-31', 175.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-05-31', 140.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Juliano Mateus ferreira', 'Sessões', '2025-05-31', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Mara Cely dos Santos Fernandes', 'Sessões', '2025-05-31', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2025-06-01', 14.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Hospedagem Site', 'Hospedagem Site', '2025-06-01', 54.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2025-06-01', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-06-01', 3453.98);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-06-01', 1245.47);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2025-06-01', 117.56);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Kommo', 'Kommo', '2025-06-01', 238.62);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2025-06-01', 12.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Energia elétrica', 'Energia elétrica', '2025-06-01', 237.59);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', '- - Secretária', NULL, '2025-06-02', 450.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Internet', 'Internet', '2025-06-02', 118.93);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Água', 'Água', '2025-06-02', 161.91);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-06-02', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Daniel Vitor Galdino', 'Sessões', '2025-06-03', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ana Carolina de Oliveira', 'Sessões', '2025-06-04', 600.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ana Carolina de Oliveira', 'Sessões', '2025-06-04', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Guilherme Almeida Alecrim', 'Sessões', '2025-06-04', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-06-05', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tirza Almeida Deschamps', 'Sessões', '2025-06-05', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Jussara Oliveira de Aguiar Marques', 'Sessões', '2025-06-05', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Soraia Paes Grama', 'Sessões', '2025-06-05', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-07', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-07', 175.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-07', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-07', 83.33);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Contabilidade', 'Contabilidade', '2025-06-09', 160.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Bot conversa', 'Sessões', '2025-06-09', 900.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-10', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Renata Martins', 'Sessões', '2025-06-10', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Jefferson de Souza Pinto', 'Sessões', '2025-06-11', 900.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Juliano Mateus ferreira', 'Sessões', '2025-06-13', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tallytta Sarah V Silva', 'Sessões', '2025-06-16', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tirza Almeida Deschamps', 'Sessões', '2025-06-16', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Marcio Gleison de Oliveira Saraiva', 'Sessões', '2025-06-16', 300.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carmem Laenia Girão de Oliveira', 'Sessões', '2025-06-16', 300.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucy Assef', 'Sessões', '2025-06-17', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-21', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-21', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-23', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-23', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-06-23', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tirza Almeida Deschamps', 'Sessões', '2025-06-23', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Soraia Paes Grama', 'Sessões', '2025-06-23', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Cintia Grigoletto', 'Sessões', '2025-06-25', 750.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-06-28', 140.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2025-06-30', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Água', 'Água', '2025-06-30', 161.91);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2025-07-01', 14.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Hospedagem Site', 'Hospedagem Site', '2025-07-01', 54.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Internet', 'Internet', '2025-07-01', 118.93);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2025-07-01', 120.49);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Kommo', 'Kommo', '2025-07-01', 238.59);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2025-07-01', 129.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-07-01', 1308.66);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Ensaio IA', 'Ensaio IA', '2025-07-01', 5.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Secretária', 'Secretária', '2025-07-01', 450.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Energia elétrica', 'Energia elétrica', '2025-07-01', 241.94);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Diego Fidelis', 'Sessões', '2025-07-01', 299.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Hospedagem IA', 'Hospedagem IA', '2025-07-02', 563.88);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-07-03', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tirza Almeida Deschamps', 'Sessões', '2025-07-06', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-07-07', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Willy Sarahan', 'Sessões', '2025-07-07', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Contabilidade', 'Contabilidade', '2025-07-09', 160.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-07-14', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tirza Almeida Deschamps', 'Sessões', '2025-07-14', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Liliane F Santos Leite', 'Sessões', '2025-07-15', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Jairo Costa e Silva', 'Sessões', '2025-07-15', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tallytta Sarah V Silva', 'Sessões', '2025-07-18', 240.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-07-21', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-07-21', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-07-21', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Daniele Rodrigues Harder', 'Sessões', '2025-07-22', 299.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Soraia Paes Grama', 'Sessões', '2025-07-23', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucy Assef', 'Sessões', '2025-07-24', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tirza Almeida Deschamps', 'Sessões', '2025-07-26', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tirza Almeida Deschamps', 'Sessões', '2025-07-26', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Willian Macel', 'Sessões', '2025-07-28', 299.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-07-29', 175.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-07-30', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-07-30', 210.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Diego Fidelis', 'Sessões', '2025-07-30', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2025-07-31', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2025-08-01', 19.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Contabilidade', 'Contabilidade', '2025-08-01', 160.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2025-08-01', 60.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2025-08-01', 112.51);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Kommo', 'Kommo', '2025-08-01', 477.18);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2025-08-01', 259.80);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Secretária', 'Secretária', '2025-08-01', 450.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-08-01', 3698.68);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-08-01', 902.58);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Água', 'Água', '2025-08-01', 147.78);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Cursos - N8N', 'Cursos', '2025-08-01', 497.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-08-04', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-08-04', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Melina Rombach', 'Sessões', '2025-08-06', 299.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carlos Rocha', 'Sessões', '2025-08-13', 192.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-08-15', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-08-15', 210.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carlos Rocha', 'Sessões', '2025-08-15', 2200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carlos Rocha', 'Sessões', '2025-08-15', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Daniel Alves Rodrigues', 'Sessões', '2025-08-19', 299.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Daniel Alves Rodrigues', 'Sessões', '2025-08-21', 2250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Diego Fidelis', 'Sessões', '2025-08-22', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Nathalia Cristina Araujo de Oliveira', 'Sessões', '2025-08-22', 750.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-08-26', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Liliane F Santos Leite', 'Sessões', '2025-08-26', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-08-27', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2025-09-01', 14.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Contabilidade', 'Contabilidade', '2025-09-01', 160.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2025-09-01', 120.18);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Kommo', 'Kommo', '2025-09-01', 238.62);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2025-09-01', 129.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-09-01', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-09-01', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-09-01', 2016.38);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-09-01', 2266.76);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-09-08', 105.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-09-10', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-09-17', 140.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-09-17', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-09-22', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Liliane F Santos Leite', 'Sessões', '2025-09-22', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Paullynne Albertins', 'Sessões', '2025-09-26', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-09-29', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Sarah Rombach', 'Sessões', '2025-09-30', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Anderson Nunes Silva de Freitas', 'Sessões', '2025-09-30', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Fernanda Lopes Sutil', 'Sessões', '2025-09-30', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2025-10-01', 14.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Contabilidade', 'Contabilidade', '2025-10-01', 160.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2025-10-01', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2025-10-01', 173.53);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Kommo', 'Kommo', '2025-10-01', 238.59);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2025-10-01', 129.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-10-01', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-10-01', 2299.44);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-10-01', 2999.98);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Paullynne Albertins', 'Sessões', '2025-10-02', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rayane Stephanie Santos Almeida', 'Sessões', '2025-10-02', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-10-06', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Milena Machado Leite', 'Sessões', '2025-10-06', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Débora Maressa', 'Sessões', '2025-10-07', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Elisângela', 'Sessões', '2025-10-07', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Anderson Nunes Silva de Freitas', 'Sessões', '2025-10-08', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walef', 'Sessões', '2025-10-08', 650.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Natalia Panta Silva Longo', 'Sessões', '2025-10-09', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Elisângela', 'Sessões', '2025-10-09', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-10-10', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-10-10', 35.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wanderley do Amaral Souza Junior', 'Sessões', '2025-10-10', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rayane Stephanie Santos Almeida', 'Sessões', '2025-10-13', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Fernanda Lopes Sutil', 'Sessões', '2025-10-15', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Alane Galvão', 'Sessões', '2025-10-15', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Beatriz de Moura Nogueira Oricoli', 'Sessões', '2025-10-16', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Munique Nannyele Rodrigues Lacerda', 'Sessões', '2025-10-17', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tallytta Sarah V Silva', 'Sessões', '2025-10-20', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Daniella Rocha de Alencar Alves', 'Sessões', '2025-10-21', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-10-22', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Débora Maressa', 'Sessões', '2025-10-24', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Hugo Maciel de Barros', 'Sessões', '2025-10-24', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Anne Karine Campos de Araújo', 'Sessões', '2025-10-27', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Larissa Fernanda Barbosa', 'Sessões', '2025-10-28', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Nicolle Yasmin Santos Lopes', 'Sessões', '2025-10-28', 240.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Anne Karine Campos de Araújo', 'Sessões', '2025-10-29', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Débora Maressa', 'Sessões', '2025-10-30', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Inajara Lima Nunes', 'Sessões', '2025-10-30', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Deborah Lyssa Sousa de Oliveira', 'Sessões', '2025-10-31', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Contabilidade', 'Contabilidade', '2025-11-01', 160.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2025-11-01', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Secretária', 'Secretária', '2025-11-01', 750.25);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tamara Jessika dos Santos Leal', 'Sessões', '2025-11-03', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2025-11-04', 14.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2025-11-04', 120.18);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Kommo', 'Kommo', '2025-11-04', 238.62);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2025-11-04', 129.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-11-04', 2299.44);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-11-04', 2999.98);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-11-04', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Liliane F Santos Leite', 'Sessões', '2025-11-04', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rayle', 'Sessões', '2025-11-04', 600.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Anne Karine Campos de Araújo', 'Sessões', '2025-11-04', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Inajara Lima Nunes', 'Sessões', '2025-11-04', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Jonas Da Silva Pereira', 'Sessões', '2025-11-04', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Alane Galvão', 'Sessões', '2025-11-05', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Deborah Lyssa Sousa de Oliveira', 'Sessões', '2025-11-05', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Djonny Weslley da Silva', 'Sessões', '2025-11-05', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Djonny Weslley da Silva', 'Sessões', '2025-11-06', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Fernanda Lopes Sutil', 'Sessões', '2025-11-07', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Edinaide da Silva Paiva Pereira', 'Sessões', '2025-11-10', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rayane Stephanie Santos Almeida', 'Sessões', '2025-11-12', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walef', 'Sessões', '2025-11-12', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Deborah Lyssa Sousa de Oliveira', 'Sessões', '2025-11-12', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aline Barbosa da Fonseca', 'Sessões', '2025-11-12', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carlos Eduardo Araújo Rocha 2', 'Sessões', '2025-11-12', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2025-11-13', 70.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Edinaide da Silva Paiva Pereira', 'Sessões', '2025-11-14', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-11-19', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wanderley do Amaral Souza Junior', 'Sessões', '2025-11-26', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Débora Maressa', 'Sessões', '2025-11-28', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Gildenise Moreira Arnaut', 'Sessões', '2025-11-28', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Liliane F Santos Leite', 'Sessões', '2025-12-01', 2000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-12-02', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2025-12-03', 19.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2025-12-03', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2025-12-03', 167.40);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Kommo', 'Kommo', '2025-12-03', 238.62);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2025-12-03', 129.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walef', 'Sessões', '2025-12-03', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Larissa Nunes Mota Possenatto', 'Sessões', '2025-12-03', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Darlene Ferreira de Moura Franco', 'Sessões', '2025-12-03', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2025-12-05', 1507.79);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2025-12-05', 4153.31);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google One', 'Google One', '2025-12-05', 4.50);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Dalila Machado Silveira', 'Sessões', '2025-12-05', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Beatriz Melo', 'Sessões', '2025-12-08', 800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Flávia Silva dos Anjos', 'Sessões', '2025-12-08', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Idelaine de Jesus Ferreira Almeida', 'Sessões', '2025-12-08', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Brenda Katriny Sousa de Oliveira', 'Sessões', '2025-12-08', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Emilly Alves de Brito', 'Sessões', '2025-12-08', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Juliana Leandro da Silva', 'Sessões', '2025-12-08', 150.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Fernanda de Oliveira Fonseca Barbosa', 'Sessões', '2025-12-08', 150.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walisson Miguel Severnini', 'Sessões', '2025-12-09', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Taise Barbosa Moitinho', 'Sessões', '2025-12-09', 150.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walef', 'Sessões', '2025-12-10', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walisson Miguel Severnini', 'Sessões', '2025-12-10', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walisson Miguel Severnini', 'Sessões', '2025-12-10', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Fernanda de Oliveira Fonseca Barbosa', 'Sessões', '2025-12-11', 600.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rafael Santos Braz da cunha', 'Sessões', '2025-12-12', 500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walef', 'Sessões', '2025-12-17', 200.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Yolle Souza Santos e Santos', 'Sessões', '2025-12-17', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Violeta Victoria Almeida Tello Gesteira', 'Sessões', '2025-12-17', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2025-12-18', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Laudicéia Tamandaré dos Santos', 'Sessões', '2025-12-18', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Luiza Cristina Araújo Martins', 'Sessões', '2025-12-18', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Laudicéia Tamandaré dos Santos', 'Sessões', '2025-12-19', 1680.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Raphael de Souza Silva', 'Sessões', '2025-12-19', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Jefferson de Souza Pinto', 'Sessões', '2025-12-22', 900.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Raphael de Souza Silva', 'Sessões', '2025-12-22', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Antonio Francisco Lima de Sousa.', 'Sessões', '2025-12-28', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Débora Maressa', 'Sessões', '2025-12-30', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walef', 'Sessões', '2025-12-30', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Larissa Nunes Mota Possenatto', 'Sessões', '2025-12-30', 1250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Larissa Nunes Mota Possenatto', 'Sessões', '2025-12-30', 750.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Viviane Maria de Sousa', 'Sessões', '2025-12-30', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Viviane Maria de Sousa', 'Sessões', '2025-12-30', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Daniela Matos Marques', 'Sessões', '2025-12-30', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Charlene Moura Marques Dias', 'Sessões', '2025-12-31', 150.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Secretária', 'Secretária', '2026-01-01', 907.50);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2026-01-01', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google One', 'Google One', '2026-01-02', 4.50);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2026-01-02', 4864.93);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads - Impulsionar', 'Meta Ads', '2026-01-02', 653.31);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2026-01-02', 168.45);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Outros - Replicate', 'Outros', '2026-01-02', 17.29);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2026-01-02', 19.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Giovana Costa Reis', 'Sessões', '2026-01-05', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Patricia Wolf Lopes', 'Sessões', '2026-01-05', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2026-01-06', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Luiza Cristina Araújo Martins', 'Sessões', '2026-01-07', 920.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Daniela Matos Marques', 'Sessões', '2026-01-07', 920.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucélia Ferreira Silva', 'Sessões', '2026-01-07', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucélia Ferreira Silva', 'Sessões', '2026-01-09', 230.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aywme Mayara de Souza Linhares', 'Sessões', '2026-01-09', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Alessandra Mendes', 'Sessões', '2026-01-09', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Charlene Moura Marques Dias', 'Sessões', '2026-01-12', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Victoria Rayane Rodrigues de Vasconcelos', 'Sessões', '2026-01-12', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Patricia Wolf Lopes', 'Sessões', '2026-01-13', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Alessandra Mendes', 'Sessões', '2026-01-13', 920.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Eglisse Lima da Silva', 'Sessões', '2026-01-13', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Matheus Lima da Silva', 'Sessões', '2026-01-14', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2026-01-18', 2114.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2026-01-18', 1304.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2026-01-18', 585.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2026-01-19', 60.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões', 'Sessões', '2026-01-19', 3000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aranir de Jesus Sousa', 'Sessões', '2026-01-20', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2026-01-21', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rafael Santos Braz da cunha', 'Sessões', '2026-01-21', 1680.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Noandra Pedrosa Souza', 'Sessões', '2026-01-22', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aranir de Jesus Sousa', 'Sessões', '2026-01-23', 210.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Marcelo dos Santos de Almeida', 'Sessões', '2026-01-26', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aranir de Jesus Sousa', 'Sessões', '2026-01-28', 210.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Erika Alves de Almeida', 'Sessões', '2026-01-28', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Geismair Gisele Barbosa de Carvalho', 'Sessões', '2026-01-28', 280.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carolina Mineli Cabral', 'Sessões', '2026-01-28', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Roberto Luiz de Almeida patene', 'Sessões', '2026-01-28', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Vanessa Ferreira da Silva Ribeiro', 'Sessões', '2026-01-28', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aline Lucas Mendonça', 'Sessões', '2026-01-30', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Laisa Adelia', 'Sessões', '2026-01-30', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Bruna wenzel', 'Sessões', '2026-01-30', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rafael Santos Braz da cunha', 'Sessões', '2026-01-31', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aranir de Jesus Sousa', 'Sessões', '2026-01-31', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google One', 'Google One', '2026-02-02', 4.50);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2026-02-02', 4804.17);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Tik Tok Ads', 'Tik Tok Ads', '2026-02-02', 160.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Api Wpp', 'Api Wpp', '2026-02-02', 9.52);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2026-02-02', 140.25);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Secretária', 'Secretária', '2026-02-02', 805.25);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2026-02-02', 129.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2026-02-02', 19.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'CRP', 'CRP', '2026-02-02', 114.58);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2026-02-02', 968.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2026-02-02', 100.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Remuneração', 'Remuneração', '2026-02-02', 320.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Débora Maressa', 'Sessões', '2026-02-02', 550.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Charlene Moura Marques Dias', 'Sessões', '2026-02-02', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Thaizy Alves de Jesus', 'Sessões', '2026-02-02', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rayssa Felix Scarlecio', 'Sessões', '2026-02-03', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Mônica Ferreira Teixeira', 'Sessões', '2026-02-03', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aranir de Jesus Sousa', 'Sessões', '2026-02-04', 210.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rayssa Felix Scarlecio', 'Sessões', '2026-02-04', 500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Priscila Lopes Dias', 'Sessões', '2026-02-05', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - YURI CAINÃ NUNES DA COSTA', 'Sessões', '2026-02-05', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Luiz Antonio Ribeiro', 'Sessões', '2026-02-05', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Roberto Luiz de Almeida patene', 'Sessões', '2026-02-06', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Luiz Antonio Ribeiro', 'Sessões', '2026-02-06', 1500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Jefferson de Souza Pinto', 'Sessões', '2026-02-09', 900.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Michaelle Ferreira Souto de Oliveira', 'Sessões', '2026-02-09', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Michael Schneider', 'Sessões', '2026-02-09', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Guilherme dos Santos Gonçalves Dias', 'Sessões', '2026-02-10', 500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Carlos Rocha', 'Sessões', '2026-02-11', 2800.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aranir de Jesus Sousa', 'Sessões', '2026-02-11', 210.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Michaelle Ferreira Souto de Oliveira', 'Sessões', '2026-02-11', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Michael Schneider', 'Sessões', '2026-02-11', 3000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Charlion Sousa da Silva', 'Sessões', '2026-02-13', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Guilherme dos Santos Gonçalves Dias', 'Sessões', '2026-02-16', 1500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2026-02-19', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aranir de Jesus Sousa', 'Sessões', '2026-02-19', 210.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rayssa Felix Scarlecio', 'Sessões', '2026-02-19', 350.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tiago Xavier Torres', 'Sessões', '2026-02-19', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ryane Cristina Galdino do Prado', 'Sessões', '2026-02-20', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Samara Lopes Freitas', 'Sessões', '2026-02-20', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rodrigo', 'Sessões', '2026-02-23', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Kleiton Nóbrega', 'Sessões', '2026-02-26', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rayssa Felix Scarlecio', 'Sessões', '2026-02-27', 350.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rodrigo', 'Sessões', '2026-02-27', 350.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Secretária', 'Secretária', '2026-03-01', 710.60);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2026-03-01', 3241.45);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2026-03-01', 129.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2026-03-01', 19.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões', 'Sessões', '2026-03-01', 3000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'CRP', 'CRP', '2026-03-02', 114.58);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Romilson Ramos Cordeiro', 'Sessões', '2026-03-02', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Simone de Oliveira Ramos', 'Sessões', '2026-03-02', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rômulo Barbosa Nicolae', 'Sessões', '2026-03-02', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2026-03-03', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rayssa Felix Scarlecio', 'Sessões', '2026-03-03', 350.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Aranir de Jesus Sousa', 'Sessões', '2026-03-04', 210.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rodrigo', 'Sessões', '2026-03-05', 350.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Fernanda Rafaela Souza Nunes Lima', 'Sessões', '2026-03-05', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Rodrigo', 'Sessões', '2026-03-06', 350.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Kamila de Lima Santos', 'Sessões', '2026-03-07', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Michaelle Ferreira Souto de Oliveira', 'Sessões', '2026-03-09', 1250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Kamila de Lima Santos', 'Sessões', '2026-03-09', 4000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Vianne', 'Sessões', '2026-03-10', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Walisson Miguel Severnini', 'Sessões', '2026-03-11', 500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Alba Valéria Santos de Oliveira', 'Sessões', '2026-03-11', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Alba Valéria Santos de Oliveira', 'Sessões', '2026-03-12', 3000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2026-03-16', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Samiris Costa dos Reis', 'Sessões', '2026-03-16', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Natalia costa de oliveira correia', 'Sessões', '2026-03-19', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tallytta Sarah V Silva', 'Sessões', '2026-03-20', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Renata', 'Sessões', '2026-03-20', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Flávio Augusto Lima Benedito', 'Sessões', '2026-03-20', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Thaynis da Silva Araújo', 'Sessões', '2026-03-23', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Adelmo Dyones Lisboa Batista', 'Sessões', '2026-03-23', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Maria Alline Euzebio', 'Sessões', '2026-03-25', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2026-03-30', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Tatiane de Jesus souza', 'Sessões', '2026-03-31', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google One', 'Google One', '2026-04-01', 14.49);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Meta Ads', 'Meta Ads', '2026-04-01', 3946.84);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Icloud', 'Icloud', '2026-04-01', 5.90);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'OpenAI', 'OpenAI', '2026-04-01', 82.23);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Telefone celular', 'Telefone celular', '2026-04-01', 39.99);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Secretária', 'Secretária', '2026-04-01', 450.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Psicomanager', 'Psicomanager', '2026-04-01', 220.31);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'CRP', 'CRP', '2026-04-01', 114.58);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Google Ads', 'Google Ads', '2026-04-01', 410.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Hospedagem Site', 'Hospedagem Site', '2026-04-01', 246.96);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Luana Stefany Alves Ferreira', 'Sessões', '2026-04-06', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucas Sousa', 'Sessões', '2026-04-06', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Wagner de Carvalho Ferreira', 'Sessões', '2026-04-07', 170.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Ronaldo Francelino da Silva', 'Sessões', '2026-04-07', 500.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('saida', 'Carnê leão', 'Carnê leão', '2026-04-09', 407.88);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões', 'Sessões', '2026-04-13', 3000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Gabriela Simões Nunes', 'Sessões', '2026-04-13', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucas HERO', 'Sessões', '2026-04-13', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Beatriz de Sousa Alves', 'Sessões', '2026-04-13', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lorhana Lisboa Ribeiro', 'Sessões', '2026-04-13', 3000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Estefania do Nascimento', 'Sessões', '2026-04-13', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Luana Stefany Alves Ferreira', 'Sessões', '2026-04-14', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Felipe Moreira Abrão', 'Sessões', '2026-04-15', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Kadmo Thalis Gomes lira', 'Sessões', '2026-04-15', 350.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Lucas Sousa', 'Sessões', '2026-04-16', 1000.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Deusimar Navarro de Abreu', 'Sessões', '2026-04-16', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Nara Raianne Oliveira Pires', 'Sessões', '2026-04-17', 250.00);
INSERT INTO financial_entries (tipo, descricao, categoria, data, valor) VALUES ('entrada', 'Sessões - Fabiana Alves da Silva', 'Sessões', '2026-04-17', 250.00);
